version: '3'
services:
  WindturbineDB:
    image: neo4j:latest
    container_name: LondonDB
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - .dbs\LondonDB:/data
    environment:
      NEO4J_AUTH: none
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4JLABS_PLUGINS: "[\"apoc\"]"